on init:
    # iron hammer
    set {_iron_hammer} to iron pickaxe with lore "Hammer" named "Iron Hammer"
    register new shaped recipe for {_iron_hammer} using iron ingot, iron block, iron ingot, air, stick, air, air, stick and air with id "iron_hammer"

    # rotten flesh to leather
    register new campfire recipe for leather using rotten flesh with id "campfire_leather" with cook time 30 seconds

